[package]
name = "wanderball"
version = "0.1.0"
authors = ["Shea Newton <shnewto@gmail.com>"]
edition = "2018"

[dependencies]
amethyst =  "0.15"
amethyst_rendy = "0.15.3"

[features]
default = []
metal = ["amethyst_rendy/metal"]
vulkan = ["amethyst_rendy/vulkan"]
