[package]
name = "wanderball"
version = "0.1.0"
authors = ["Shea Newton <shnewto@gmail.com>"]
edition = "2018"

[dependencies.amethyst]
version =  "0.15"
features = ["metal"]

[dependencies]
serde = "1.0.116"
